feat: read file during reconstruction
thrumdev/bitbox pull request #34
Opened 2024-07-21 20:55 UTC by rphmeier

2024-07-21 20:55 UTC, rphmeier commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/34?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#34** <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/34?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#33** <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/33?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#32** <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/32?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#31** <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/31?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#30** <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/30?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rphmeier and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-22 13:49 UTC, pepyakin requested changes, later dismissed
Perhaps not immediatelly obvious and not stated anywhere explicitly (maybe briefly in meta.rs) but the first page of BBN and LN storages are reserved. The reason is two-fold:

1. to have a notion of NULL pointer for specifying the end of a linked-list e.g. for freelist. (It is used for LN storage and we are discussing it for BBN storage)
2. just to reserve some space for some data. I am not entirely sure under which circumstances we would need it, given that we already have an entire metadata file dedicated for that stuff, but who knows.

so for this code, this basically implies we should just skip the first page.

2024-07-22 13:53 UTC, pepyakin commented on src/beatree/ops/reconstruction.rs
> +const READ_CHUNK_SIZE: usize = BRANCH_NODE_SIZE * 64;
Nit: or `SEQ_READ_CHUNK_LEN` ? : )

2024-07-22 13:54 UTC, pepyakin commented on src/beatree/ops/reconstruction.rs
> +const READ_CHUNK_SIZE: usize = BRANCH_NODE_SIZE * 64;
Nit: or `SEQ_READ_CHUNK_LEN` ? : )

2024-07-22 13:54 UTC, pepyakin commented on src/beatree/ops/reconstruction.rs
> +type SeqReadChunk = [u8; READ_CHUNK_SIZE];
Nit: or `SEQ_READ_CHUNK_LEN`

2024-07-22 16:53 UTC, rphmeier commented
Thanks for clarifying. I've updated the PR to skip the first page.

2024-07-22 16:57 UTC, rphmeier commented
### Merge activity

* **Jul 22, 12:57 PM EDT**: @rphmeier started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/thrumdev/bitbox/34).

2024-07-22 17:06 UTC, merged